### ISSUE TITLE
Helioviewer To Do List

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#252]
This issue is being used to keep a note of larger tasks.  This will be edited as new tasks appear and as the tasks listed get their own GitHub issues.

- [ ] Convert final archive RHESSI FITS images to JPEG2000 - now tracked as a separate issue at https://github.com/Helioviewer-Project/jp2gen/issues/33
- [ ] Convert final archive TRACE FITS images to JPEG2000 - now tracked as a separate issue at https://github.com/Helioviewer-Project/jp2gen/issues/28
- [x] Convert archived and current KCor FITS images to JPEG2000. See #239, https://github.com/NCAR/kcor-pipeline/issues/85
- [x] Convert archived and current SUVI FITS images to JPEG2000.
- [ ] Take output from the Hannah & Kontar DEM algorithm and convert that data to JPEG2000 - now tracked as a separate issue at https://github.com/Helioviewer-Project/jp2gen/issues/44
- [ ] Redo all the existing LASCO JPEG2000 images using the Level 1 data and not the quicklook Level 0.5 data - tracked at https://github.com/Helioviewer-Project/jp2gen/issues/17
- [ ] Set up a process that automatically replaces LASCO JPEG2000 images from more than 6 months ago with images that are made using good backgrounds (note - find out how long it takes to create a good background for LASCO) - now tracked at https://github.com/Helioviewer-Project/jp2gen/issues/45 
- [x] Fix the EIT JPEG2000 creation pipeline (no new EIT images since 2013) - now tracked via https://github.com/Helioviewer-Project/jp2gen/issues/15
- [ ] Redo all the existing COR JPEG200 images using good backgrounds - now tracked at https://github.com/Helioviewer-Project/jp2gen/issues/46
- [ ] Set up a process that automatically replaces COR JPEG2000 images from more than 2 months ago with images that are made using good backgrounds - now tracked at https://github.com/Helioviewer-Project/jp2gen/issues/47
- [ ] Local AIA and HMI FITS to JPEG2000 image creation that is automatically triggered when large gaps appear in the standard JPEG2000 stream appears - now tracked via https://github.com/Helioviewer-Project/jp2gen/issues/48
- [ ] Some way to test that JHelioviewer is able to obtain and stream a movie.  This test should be run regularly and frequently with notifications being sent out when it fails - tracked via https://github.com/Helioviewer-Project/helioviewer.org/issues/249
- [ ] Improved monitoring of image creation and image provision services - now tracked via https://github.com/Helioviewer-Project/jp2gen/issues/49
- [ ] Improved monitoring of the obtaining of HEK event information - now tracked via https://github.com/Helioviewer-Project/helioviewer.org/issues/436
- [x] Improved usage statistic collection that is run regularly and frequently.
- [x] Labeling of planets (with accurate planet transit paths) and other objects (Parker Solar Probe, Solar Orbiter, STEREO A, B) in the SOHO field of view.
- [x] Labeling of planets (with accurate planet transit paths) and other objects (Parker Solar Probe, Solar Orbiter, STEREO A, B, SOHO) in the STEREO A, B field of view.
- [ ] Inclusion of information about SUMER observations - how best to do this?  This will also be an important test case to understand how to include spectroscopic information more generally (e.g, Hinode EIS, SOHO CDS, IRIS) - now tracked via https://github.com/Helioviewer-Project/jp2gen/issues/43

**Comment by wafels** [comment]
These should be split up into different issues.

**Comment by wafels** [comment]
All the issues in the to-do list now point to existing open and closed issues elsewhere. I am going to close this issue since progress on the smorgasbord of issues above can be tracked separately.
